### ISSUE TITLE
검색이 안됩니다.

### ISSUE THREAD

**Issue by jungsikjeong** [2skydev/Notion-Next.js-blog-starter-kit#62]
혹시 어떤 해결방안이있을까요?

**Comment by 2skydev** [comment]
검색이 노션 검색 말씀하시는 것 맞을까요?

현재 노션 검색이 안되는 것으로 보이며 노션 공식 API가 아닌 내부 API를 사용하는 방식이라 노션팀에서 변경하여 생긴 문제 같습니다.
직접 검색 관련해서 API를 찾아서 수정하거나 검색 아이콘을 지우는 방법 말고는 없을 것 같습니다 ㅜㅜ

아무래도 비공식 노션 내부 API를 사용하는 것이라 불안정합니다.
추후 시간되면 직접 블로그 킷 만들어보려고 합니다

**Comment by jeonghyeon00** [comment]
PR 올려봤습니다 https://github.com/2skydev/Notion-Next.js-blog-starter-kit/pull/65

**Comment by 2skydev** [comment]
@jeonghyeon00 님의 PR로 검색 문제 해결되었습니다! 감사합니다 :D

cc @jungsikjeong

**Comment by jungsikjeong** [comment]
@jeonghyeon00 안녕하세요 프로필에서 블로그를 들어가봤는데 게시글을 클릭하면 에러페이지가 나오네욥.. 혹시 알고계신가해서 댓글남깁니다. 그리고 문제 해결 감사드립니다.

**Comment by jeonghyeon00** [comment]
> @jeonghyeon00 안녕하세요 프로필에서 블로그를 들어가봤는데 게시글을 클릭하면 에러페이지가 나오네욥.. 혹시 알고계신가해서 댓글남깁니다. 그리고 문제 해결 감사드립니다.
@jungsikjeong 
404 뜨나요?? 다시 한번 빌드해보시겠어요?? 저는 잘되네요

**Comment by jungsikjeong** [comment]
@jeonghyeon00  아! 지금 님 블로그 들어가보니까 이제 에러안뜨네요 감사합니다.

**Comment by jeonghyeon00** [comment]
> @jeonghyeon00  아! 지금 님 블로그 들어가보니까 이제 에러안뜨네요 감사합니다.

아 제 블로그였군요 ㅋㅋ

**Comment by jungsikjeong** [comment]
@jeonghyeon00  님 안녕하세요!
 2skydev님의 블로그 검색api를 해결해주셔서 저도 이제 블로그를 이걸로 정착하려고 합니다.

다름아니라, 님 블로그를 방문해서 살펴봤을때 게시글 카테고리 드랍다운 메뉴가 다크모드가 적용이 안된걸 발견했습니다.
저도 님과 같이 드랍다운 메뉴로 설정을 해줬는데 이와같은 현상이 똑같이 발생해서 제가 한번 해결해봤는데요.

.notion.scss
```css
.notion-collection-view-dropdown-content-item {
  background-color: var(--bg-color);
  color: var(--fg-color);
  fill: var(--fg-color);

  &:hover {
    background-color: var(--bg-color-1);

  }
}
.notion-collection-view-type {
  .notion-collection-view-dropdown-icon {
    fill: var(--fg-color);
  }

  .notion-collection-view-type-icon {
    fill: var(--fg-color);
  }
}

```
이렇게 스타일링 줘서 해결했습니당..
감사합니다
